---
all:
  vars:
    user: uncork
    ssh_key : ~/.ssh/ansible

  hosts: 
    web:    
      ansible_host: 192.168.92.201
      ansible_ssh_private_key_file: "{{ ssh_key }}"
      ansible_user: "{{ user }}"
      ansible_ssh_port: 32111
