---
- name: Remove Apache2
  hosts: web
  become: yes
  tasks:
    - name: Update repository index
      apt: 
        update_cache: yes
        
    - name: Remove Apache
      apt:
        name: apache2
        state: absent
